name: kite
description: "Kite"

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  path: any
  go_router: ^14.8.1
  get_it: ^8.0.3
  collection: ^1.19.1
  pull_down_button: ^0.10.2
  intl: ^0.20.2
  flutter_widget_from_html_core: ^0.16.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.9.4
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - assets/
